-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.affiliate_attributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_item_id uuid NOT NULL UNIQUE,
  order_id uuid NOT NULL,
  content_id uuid NOT NULL,
  product_id uuid NOT NULL,
  content_product_tag_id uuid,
  creator_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  click_id uuid,
  attribution_model character varying DEFAULT 'last_click'::character varying CHECK (attribution_model::text = ANY (ARRAY['last_click'::character varying, 'first_click'::character varying]::text[])),
  attributed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_attributions_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_attributions_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT affiliate_attributions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT affiliate_attributions_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id),
  CONSTRAINT affiliate_attributions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT affiliate_attributions_content_product_tag_id_fkey FOREIGN KEY (content_product_tag_id) REFERENCES public.content_product_tags(id),
  CONSTRAINT affiliate_attributions_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_attributions_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_attributions_click_id_fkey FOREIGN KEY (click_id) REFERENCES public.affiliate_clicks(id)
);
CREATE TABLE public.affiliate_clicks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  content_id uuid NOT NULL,
  product_id uuid NOT NULL,
  content_product_tag_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  session_id character varying NOT NULL,
  ip_address inet,
  user_agent text,
  referrer text,
  clicked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_clicks_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_clicks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT affiliate_clicks_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id),
  CONSTRAINT affiliate_clicks_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT affiliate_clicks_content_product_tag_id_fkey FOREIGN KEY (content_product_tag_id) REFERENCES public.content_product_tags(id),
  CONSTRAINT affiliate_clicks_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_clicks_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id)
);
CREATE TABLE public.affiliate_earnings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  order_item_id uuid NOT NULL UNIQUE,
  attribution_id uuid NOT NULL,
  product_id uuid NOT NULL,
  content_id uuid NOT NULL,
  order_amount integer NOT NULL,
  commission_rate numeric NOT NULL,
  commission_amount integer NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'paid'::character varying, 'cancelled'::character varying]::text[])),
  earned_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  paid_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  notes text,
  CONSTRAINT affiliate_earnings_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_earnings_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_earnings_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_earnings_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT affiliate_earnings_attribution_id_fkey FOREIGN KEY (attribution_id) REFERENCES public.affiliate_attributions(id),
  CONSTRAINT affiliate_earnings_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT affiliate_earnings_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id)
);
CREATE TABLE public.affiliate_partnerships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'active'::character varying, 'inactive'::character varying, 'rejected'::character varying]::text[])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  deactivated_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_partnerships_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_partnerships_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_partnerships_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_partnerships_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.affiliate_product_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  product_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  requested_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  creator_message text,
  brand_response text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_product_requests_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_product_requests_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_product_requests_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_product_requests_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT affiliate_product_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.affiliate_wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  product_id uuid NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT affiliate_wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_wishlist_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT affiliate_wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.app_version (
  id integer NOT NULL DEFAULT nextval('app_version_id_seq'::regclass),
  platform text NOT NULL,
  min_version text NOT NULL,
  latest_version text NOT NULL,
  force_update boolean DEFAULT false,
  update_message text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT app_version_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cancel_exchange_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_item_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['cancel'::character varying::text, 'refund'::character varying::text, 'exchange'::character varying::text])),
  reason character varying NOT NULL,
  detail text,
  status character varying NOT NULL DEFAULT '''pending''::character varying'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'processing'::character varying, 'completed'::character varying]::text[])),
  admin_note text,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  image_url ARRAY,
  CONSTRAINT cancel_exchange_requests_pkey PRIMARY KEY (id),
  CONSTRAINT cancel_exchange_requests_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT cancel_exchange_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.content_product_tags (
  start_time numeric NOT NULL,
  end_time numeric NOT NULL,
  position_x numeric NOT NULL,
  position_y numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  contents_id uuid,
  image_index integer DEFAULT 0,
  show_image boolean DEFAULT true,
  CONSTRAINT content_product_tags_pkey PRIMARY KEY (id),
  CONSTRAINT content_product_tags_contents_id_fkey FOREIGN KEY (contents_id) REFERENCES public.contents(id),
  CONSTRAINT reel_product_tags_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.contents (
  creator_id uuid,
  video_url text,
  thumbnail_url text,
  thumbnail_second numeric DEFAULT 0,
  description text,
  keywords ARRAY DEFAULT '{}'::text[],
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  short_code text UNIQUE,
  store_name text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type character varying DEFAULT 'video'::character varying CHECK (content_type::text = ANY (ARRAY['video'::character varying, 'image'::character varying]::text[])),
  image_urls ARRAY,
  ig_contents_code text,
  CONSTRAINT contents_pkey PRIMARY KEY (id),
  CONSTRAINT reels_store_name_fkey FOREIGN KEY (store_name) REFERENCES public.seller_store(store_name),
  CONSTRAINT reels_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_store(seller_id)
);
CREATE TABLE public.feedback (
  id integer NOT NULL DEFAULT nextval('feedback_id_seq'::regclass),
  user_id uuid,
  category text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.keywords (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  CONSTRAINT keywords_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_name text NOT NULL,
  product_price integer NOT NULL,
  quantity integer NOT NULL,
  total_price integer DEFAULT (product_price * quantity),
  created_at timestamp with time zone DEFAULT now(),
  color_name text,
  size text,
  product_id uuid,
  confirmed_at timestamp with time zone,
  prepared_at timestamp with time zone,
  shipped_at timestamp with time zone,
  shipping_company character varying,
  tracking_number character varying,
  item_delivery_status character varying DEFAULT 'preparing'::character varying,
  user_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT order_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  payment_amount integer,
  payment_status text NOT NULL DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'cancelled'::text, 'refunded'::text, 'failed'::text])),
  delivery_status text NOT NULL DEFAULT 'preparing'::text,
  created_at timestamp without time zone DEFAULT now(),
  shipping_address_id uuid,
  shipping_request text,
  payment_key text UNIQUE,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES public.user_addresses(id)
);
CREATE TABLE public.product_affiliate_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partnership_id uuid,
  product_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  creator_id uuid,
  commission_rate numeric NOT NULL CHECK (commission_rate >= 0::numeric AND commission_rate <= 100::numeric),
  commission_type character varying NOT NULL DEFAULT 'percentage'::character varying CHECK (commission_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'approved'::character varying CHECK (status::text = ANY (ARRAY['approved'::character varying, 'rejected'::character varying, 'suspended'::character varying]::text[])),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  max_uses integer,
  current_uses integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_public boolean DEFAULT false,
  CONSTRAINT product_affiliate_settings_pkey PRIMARY KEY (id),
  CONSTRAINT product_affiliate_settings_partnership_id_fkey FOREIGN KEY (partnership_id) REFERENCES public.affiliate_partnerships(id),
  CONSTRAINT product_affiliate_settings_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_affiliate_settings_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT product_affiliate_settings_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id)
);
CREATE TABLE public.product_options (
  size text,
  color_hex text,
  quantity integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  color_name text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  product_id uuid,
  CONSTRAINT product_options_pkey PRIMARY KEY (id),
  CONSTRAINT product_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  order_item_id uuid NOT NULL UNIQUE,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  images ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.products (
  seller_id uuid,
  product_name text NOT NULL,
  store_name text,
  description text,
  main_images ARRAY DEFAULT '{}'::text[],
  detail_images ARRAY DEFAULT '{}'::text[],
  status text DEFAULT 'active'::text,
  price integer DEFAULT 0,
  keywords ARRAY,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  product_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT products_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.seller_profile(id),
  CONSTRAINT products_store_name_fkey1 FOREIGN KEY (store_name) REFERENCES public.seller_store(store_name)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nick_name text NOT NULL UNIQUE,
  user_name text,
  email text NOT NULL UNIQUE,
  phone text UNIQUE,
  role text NOT NULL DEFAULT 'user'::text,
  interests ARRAY DEFAULT '{}'::text[],
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  promo boolean,
  tutorial_completed boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.seller_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  store_name text NOT NULL UNIQUE,
  store_description text,
  business_number text NOT NULL,
  business_type text DEFAULT 'individual'::text,
  owner_name text NOT NULL,
  address text,
  contact_email text NOT NULL,
  contact_phone text,
  bank_name text NOT NULL,
  bank_account text NOT NULL,
  bank_account_holder text NOT NULL,
  status text DEFAULT 'pending'::text,
  joined_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone,
  commission_rate numeric DEFAULT 5.00 CHECK (commission_rate >= 0::numeric AND commission_rate <= 100::numeric),
  payment_fee_rate numeric DEFAULT 3.6 CHECK (payment_fee_rate >= 0::numeric AND payment_fee_rate <= 100::numeric),
  profile_image text,
  banner_image text,
  bio text,
  social_links jsonb DEFAULT '{}'::jsonb,
  total_videos integer DEFAULT 0,
  total_followers integer DEFAULT 0,
  avg_engagement_rate numeric DEFAULT 0,
  CONSTRAINT seller_profile_pkey PRIMARY KEY (id),
  CONSTRAINT seller_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.seller_store (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL UNIQUE,
  store_name text UNIQUE CHECK (char_length(store_name) > 0),
  store_description text NOT NULL CHECK (char_length(store_description) > 0),
  promotion_text ARRAY DEFAULT '{}'::text[],
  sub_tab_title text DEFAULT 'Category'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  main_image ARRAY,
  sub_image_1 ARRAY,
  sub_image_2 ARRAY,
  sub_tab_1 text,
  sub_tab_2 text,
  sub_tab_3 text,
  sub_tab_4 text,
  logo_image text,
  search_keywords ARRAY DEFAULT '{}'::text[],
  CONSTRAINT seller_store_pkey PRIMARY KEY (id),
  CONSTRAINT seller_store_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.seller_profile(id)
);
CREATE TABLE public.settlement_generation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  generation_type character varying CHECK (generation_type::text = ANY (ARRAY['sales'::character varying, 'affiliate'::character varying, 'batch'::character varying]::text[])),
  period_start date NOT NULL,
  period_end date NOT NULL,
  seller_id uuid,
  settlement_id uuid,
  status character varying CHECK (status::text = ANY (ARRAY['success'::character varying, 'skipped'::character varying, 'failed'::character varying]::text[])),
  reason text,
  error_details jsonb,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settlement_generation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT settlement_generation_logs_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.weekly_settlements(id),
  CONSTRAINT settlement_generation_logs_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.seller_profile(id)
);
CREATE TABLE public.share2dm_brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_name text NOT NULL,
  ig_account_id text NOT NULL UNIQUE,
  ig_access_token text NOT NULL,
  token_expires_at timestamp with time zone,
  plan text DEFAULT 'free'::text CHECK (plan = ANY (ARRAY['free'::text, 'standard'::text, 'growth'::text, 'pro'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT share2dm_brands_pkey PRIMARY KEY (id)
);
CREATE TABLE public.share2dm_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_id uuid,
  reel_url text NOT NULL,
  ig_contents_id text NOT NULL,
  response_message text NOT NULL,
  product_url text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  short_code text,
  CONSTRAINT share2dm_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT share2dm_campaigns_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.share2dm_brands(id)
);
CREATE TABLE public.share2dm_dm_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  brand_id uuid,
  sender_ig_id text NOT NULL,
  reel_video_id text,
  dm_sent_at timestamp with time zone DEFAULT now(),
  link_clicked_at timestamp with time zone,
  CONSTRAINT share2dm_dm_logs_pkey PRIMARY KEY (id),
  CONSTRAINT share2dm_dm_logs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.share2dm_campaigns(id),
  CONSTRAINT share2dm_dm_logs_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.share2dm_brands(id)
);
CREATE TABLE public.shipping_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  tracking_url_template character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.store_tab_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_store_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  tab_index smallint,
  CONSTRAINT store_tab_products_pkey PRIMARY KEY (id),
  CONSTRAINT store_tab_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT store_tab_products_seller_store_id_fkey FOREIGN KEY (seller_store_id) REFERENCES public.seller_store(id)
);
CREATE TABLE public.temp_user_interactions (
  id integer NOT NULL DEFAULT nextval('temp_user_interactions_id_seq'::regclass),
  user_id uuid,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['product'::text, 'reel'::text])),
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['like'::text, 'purchase'::text])),
  interaction_score double precision DEFAULT 1.0,
  created_at timestamp with time zone DEFAULT now(),
  content_id uuid NOT NULL,
  CONSTRAINT temp_user_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT temp_user_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_addresses (
  user_id uuid NOT NULL,
  address_type text DEFAULT 'shipping'::text,
  is_default boolean DEFAULT false,
  full_name text,
  address_line1 text,
  address_line2 text,
  postal_code text,
  country text,
  phone_number text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  id uuid NOT NULL UNIQUE,
  CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  color_name text,
  size text,
  price bigint,
  product_id uuid NOT NULL,
  attribution_click_id uuid,
  CONSTRAINT user_cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT user_cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT user_cart_items_attribution_click_id_fkey FOREIGN KEY (attribution_click_id) REFERENCES public.affiliate_clicks(id)
);
CREATE TABLE public.user_initial_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp without time zone DEFAULT now(),
  keyword text NOT NULL,
  preference_score numeric DEFAULT 1.0,
  user_id uuid NOT NULL,
  CONSTRAINT user_initial_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_initial_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_keyword_preferences (
  id integer NOT NULL DEFAULT nextval('user_keyword_preferences_id_seq'::regclass),
  user_id uuid,
  keyword text NOT NULL,
  preference_score double precision DEFAULT 0.0,
  rank integer NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT user_keyword_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_keyword_preferences_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_likes_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  target_id uuid,
  CONSTRAINT user_likes_products_pkey PRIMARY KEY (id),
  CONSTRAINT user_likes_products_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_likes_products_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.user_likes_reels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  target_id uuid,
  CONSTRAINT user_likes_reels_pkey PRIMARY KEY (id),
  CONSTRAINT user_likes_reels_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_likes_reels_targer_id_fkey FOREIGN KEY (target_id) REFERENCES public.contents(id)
);
CREATE TABLE public.weekly_settlement_affiliate_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  settlement_id uuid NOT NULL,
  affiliate_earning_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  product_name text NOT NULL,
  content_id uuid,
  order_amount numeric NOT NULL,
  commission_rate numeric NOT NULL,
  commission_amount numeric NOT NULL,
  earned_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  brand_name text,
  CONSTRAINT weekly_settlement_affiliate_items_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_settlement_affiliate_items_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.weekly_settlements(id),
  CONSTRAINT weekly_settlement_affiliate_items_affiliate_earning_id_fkey FOREIGN KEY (affiliate_earning_id) REFERENCES public.affiliate_earnings(id),
  CONSTRAINT weekly_settlement_affiliate_items_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.seller_profile(id),
  CONSTRAINT weekly_settlement_affiliate_items_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id)
);
CREATE TABLE public.weekly_settlement_affiliate_refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  order_item_id uuid NOT NULL UNIQUE,
  affiliate_earning_id uuid,
  refund_type text NOT NULL CHECK (refund_type = ANY (ARRAY['cancelled'::text, 'refunded'::text])),
  refund_amount numeric NOT NULL,
  refund_date timestamp with time zone NOT NULL DEFAULT now(),
  original_settlement_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processed'::text, 'applied'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_settlement_id uuid,
  applied_at timestamp with time zone,
  product_name text,
  brand_name text,
  CONSTRAINT weekly_settlement_affiliate_refunds_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_settlement_affiliate_refunds_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.seller_profile(id),
  CONSTRAINT weekly_settlement_affiliate_refunds_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT weekly_settlement_affiliate_refunds_affiliate_earning_id_fkey FOREIGN KEY (affiliate_earning_id) REFERENCES public.affiliate_earnings(id),
  CONSTRAINT weekly_settlement_affiliate_refunds_original_settlement_id_fkey FOREIGN KEY (original_settlement_id) REFERENCES public.weekly_settlements(id),
  CONSTRAINT weekly_settlement_affiliate_refunds_applied_settlement_id_fkey FOREIGN KEY (applied_settlement_id) REFERENCES public.weekly_settlements(id)
);
CREATE TABLE public.weekly_settlement_refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  order_item_id uuid NOT NULL UNIQUE,
  refund_type character varying NOT NULL CHECK (refund_type::text = ANY (ARRAY['cancel'::character varying::text, 'refund'::character varying::text, 'exchange'::character varying::text, 'cancelled'::character varying::text, 'refunded'::character varying::text])),
  refund_amount numeric NOT NULL,
  refund_date timestamp with time zone NOT NULL,
  original_settlement_id uuid,
  applied_settlement_id uuid,
  applied_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processed'::character varying, 'applied'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_settlement_refunds_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_settlement_refunds_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.seller_profile(id),
  CONSTRAINT weekly_settlement_refunds_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT weekly_settlement_refunds_original_settlement_id_fkey FOREIGN KEY (original_settlement_id) REFERENCES public.weekly_settlements(id),
  CONSTRAINT weekly_settlement_refunds_applied_settlement_id_fkey FOREIGN KEY (applied_settlement_id) REFERENCES public.weekly_settlements(id)
);
CREATE TABLE public.weekly_settlement_sales_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  settlement_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  product_name text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  total_amount numeric NOT NULL,
  commission numeric NOT NULL,
  net_amount numeric NOT NULL,
  order_date timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_affiliate boolean DEFAULT false,
  affiliate_commission numeric DEFAULT 0,
  affiliate_commission_rate numeric DEFAULT 0,
  CONSTRAINT weekly_settlement_sales_items_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_settlement_sales_items_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.weekly_settlements(id),
  CONSTRAINT weekly_settlement_sales_items_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id)
);
CREATE TABLE public.weekly_settlements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  settlement_type character varying NOT NULL CHECK (settlement_type::text = ANY (ARRAY['sales'::character varying, 'affiliate'::character varying]::text[])),
  week_number integer NOT NULL,
  year integer NOT NULL,
  period_start_date date NOT NULL,
  period_end_date date NOT NULL,
  gross_sales numeric NOT NULL DEFAULT 0,
  refund_amount numeric NOT NULL DEFAULT 0,
  net_sales numeric NOT NULL DEFAULT 0,
  commission_rate numeric NOT NULL DEFAULT 10.00,
  commission_amount numeric NOT NULL DEFAULT 0,
  final_amount numeric NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'carried_forward'::character varying]::text[])),
  due_date date NOT NULL,
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_fee_amount numeric DEFAULT 0,
  carried_forward_amount numeric DEFAULT 0,
  approved_by uuid,
  approved_at timestamp with time zone,
  paid_by uuid,
  paid_at timestamp with time zone,
  approval_notes text,
  actual_payment_amount numeric DEFAULT 0,
  CONSTRAINT weekly_settlements_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_settlements_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.seller_profile(id),
  CONSTRAINT weekly_settlements_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT weekly_settlements_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.profiles(id)
);