name = "share2dm-webhook"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "d35802d18d8a8be726a4956153bcc895"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[vars]
ENVIRONMENT = "production"
META_APP_SECRET = "b187c2e7f226baa8c8a3ee00e598bd27"
